### ISSUE TITLE
Cannot import VPAX file

### ISSUE THREAD

**Issue by sponge2017** [sql-bi/VertiPaq-Analyzer#14]
Hi there! I tried to import a tabular model's VPAX file that was generated by DAX Studio 2.15.0 into Vertipaq Analyzer 2.02, but it was not successful, spinning wheels in front of query tables kept going forever, and finally get this error: 
(Press
![error](https://user-images.githubusercontent.com/27026127/116582127-06334d00-a8e3-11eb-88ae-ff61ff43e62c.png)
 Esc to cancel). 
I even tried creating the exact original file path, and renamed my vpax file as contoso.vpax, still no luck. 
please contact me if you need more information.
thanks!

**Comment by marcosqlbi** [comment]
Questions:
 - do you have the same error with different VPAX files?
 - if yes, can you share a VPAX file of a sample model we can analyze?
 - what is the version of Excel you have?
Thanks!

**Comment by sponge2017** [comment]
No, I didn’t get the error when I tried importing other vpax files, they all were not successful either, the spinning wheels keeps spinning, even overnight.
Attached in the vpax file that gave me the reported error.
The version of Excel is 2016 profession plus.

**Comment by marcosqlbi** [comment]
I don't see the VPAX file. Please, reply on github.com site, if you reply by email the attachment is lost.
Thanks!

**Comment by sponge2017** [comment]
I could not attach it directly because file type not accepted. so, I changed the file type as txt. hope it will go through. please rename the file back to vpax after you download it. thanks.

[Contoso.txt](https://github.com/sql-bi/VertiPaq-Analyzer/files/6401414/Contoso.txt)

**Comment by marcosqlbi** [comment]
I tried and it works correctly on my PC.
Questions:
- are you using the latest version of VertiPaq Analyzer (2.02) ?
- can you try on a more recent version of Excel? I use Excel in Microsoft 365, which is more updated than Excel 2019 - I am not able to test on Excel 2016 at the moment.

Thanks!

**Comment by sponge2017** [comment]
Thanks for looking it. Yes, I use Vertical Analyzer 2.02.I don't have Excel 2019 right now. I will try finding a 2019 to open it, and will keep you updated.On Apr 30, 2021 3:47 PM, Marco Russo ***@***.***> wrote:
I tried and it works correctly on my PC.
Questions:
are you using the latest version of VertiPaq Analyzer (2.02) ?can you try on a more recent version of Excel? I use Excel in Microsoft 365, which is more updated than Excel 2019 - I am not able to test on Excel 2016 at the moment.
Thanks!

**Comment by marcosqlbi** [comment]
Great, I keep the item open waiting for your feedback. Thanks.

**Comment by sponge2017** [comment]
Excel of office 365 works. It seems not work for lower version. Thanks much for helping!On May 1, 2021 12:13 AM, Marco Russo ***@***.***> wrote:
Great, I keep the item open waiting for your feedback. Thanks.

**Comment by marcosqlbi** [comment]
Thanks for the feedback! I updated the tool page to highlight the compatibility requirements.
You can download version 1.93 that is compatible with Excel 2016: https://www.sqlbi.com/tools/vertipaq-analyzer/

**Comment by sponge2017** [comment]
OK. Thanks for the info.On May 1, 2021 8:51 AM, Marco Russo ***@***.***> wrote:
Thanks for the feedback! I updated the tool page to highlight the compatibility requirements.
You can download version 1.93 that is compatible with Excel 2016: https://www.sqlbi.com/tools/vertipaq-analyzer/
