### ISSUE TITLE
Add Summary Information Sheet

### ISSUE THREAD

**Issue by asjones987** [sql-bi/VertiPaq-Analyzer#15]
This is tied to the DAX Studio bug 
https://github.com/DaxStudio/DaxStudio/issues/662

It would be nice if it the same summary info that DAX Studio has were also in the Excel VertiPaq Analyzer.

The summary information would include
-PBI File Name (i know that is being excluded now, but what about an option to show it? It would help with internal auditing.
-Total Size
-Number of Tables
-Number of Columns
-Last Data Refreshed (Local Time or UTC and Local)
-Analysis Date (Local Time or UTC and Local)
-Any other meta data dates?
-Server (not as critical for the Excel version
-Count of DAX Columns (something we don't want many of)
-Count of DAX Tables
-Count of DAX Measures
-Not sure this is possible, but count of automatically generated DATE tables (if they exist).

It seems like there could be some other good summary statistics and information that could be added.

I know based on comments @dgosbell is looking at some of what would be needed to pass information over etc. I think a nice summary Excel sheet would be nice for many reasons.

thanks

Alan

**Comment by marcosqlbi** [comment]
The Excel file in VertiPaq Analyzer 2.1.0 released today supports a new page with almost all of the information requested.
You have to use the next release of DAX Studio (2.17.4 or newer) that will implement the new VertiPaq Analyzer library.
