### ISSUE TITLE
No local connections available within PowerPivot to edit for SSAS (V1.93 and V2.02)

### ISSUE THREAD

**Issue by mzorob** [sql-bi/VertiPaq-Analyzer#17]
Hello,

I'm trying to use vertipaq analyzer to analyze a SSAS tabular model but there are no available connections for me to edit according to the instructions tab.  The issue is occurring in both versions 1.93 and 2.02. 

![image](https://user-images.githubusercontent.com/35414906/130803296-ba9b79c3-a543-468f-814c-5e85d42b7808.png)

When I attempt to create a new SSAS connection I'm prompted to write an MDX query. Would a potential workaround be to use the query that is used in the existing connection thats supposed to be there and if so would anyone be willing to share that? 

![image](https://user-images.githubusercontent.com/35414906/130803756-7db11e48-e99d-404e-a931-8c7df34a26d3.png)

I'm using excel in office 365 to open the workbooks, if there's any other information I missed that might help please let me know. 

Thanks,
Muhammad

**Comment by marcosqlbi** [comment]
You should follow the instructions here using DAX Studio and then importing the VPAX file with VertiPaq Analyzer 2.02:
https://www.sqlbi.com/blog/marco/2019/09/15/vertipaq-analyzer-2-0-preview-1/
