### ISSUE TITLE
Enhancement: Add Refreshed Time and State to Partition Data

### ISSUE THREAD

**Issue by corycundy** [sql-bi/VertiPaq-Analyzer#18]
Storing and showing the Last Date Refresh on the Summary tab in DAX Studio has been very useful. To take this to the next level, I think it would be very useful to store and show the Last Refresh Date of a Partition along with the Partition state in the Partitions tab. State would be secondary to Refreshed Time, but if it can come along for the ride, why not. This would be very helpful for troubleshooting.

I've been using the following query manually for quite some time and would love to have this information integrated into the vpax file and ultimately the DAX Studio view.

select [Name], [State], [ModifiedTime], [RefreshedTime] from $SYSTEM.TMSCHEMA_PARTITIONS

I realize that this DMV is not referenced yet and would likely have to be merged together with the data from the DMV where the partition information is being read from, but on the surface it seems straightforward.

State Details
https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.partition.state?view=analysisservices-dotnet

**Comment by marcosqlbi** [comment]
The new information is published in the library. However, you have to wait for the next release of DAX Studio to export the correct VPAX format and use the VertiPaq Analyzer 2.10 Excel file, which will be released soon.

**Comment by corycundy** [comment]
Thanks Marco!
