### ISSUE TITLE
No description on calculation items (DAX Expression page)

### ISSUE THREAD

**Issue by shiyanovg** [sql-bi/VertiPaq-Analyzer#20]
Hello, SQLBI Team!

I'm having a trouble with exporting some metadata to VPAX file from DAX Studio.
Specifically I would like to collect all my DAX Expressions in one place with their respective properties.
With measures or Calc Columns I have everything (DAX Expression, DisplayFolder, FormatString, IsHidden, Description).
But when I look at my Calc Items (which I made with Tabular Editor v2.16.1) I don't see Description of Calc Items.

VertiPaq Analyzer screenshot:
![image](https://user-images.githubusercontent.com/94114128/142978846-66e83710-8388-4125-82e1-b14e0b039e4d.png)

Tabular Editor screenshot:
![image](https://user-images.githubusercontent.com/94114128/142980604-fadfd58b-7815-441c-b9b3-331cc48439f5.png)

Versions used:
Tabular Editor v2.16.1
DAX Studio v2.16+

Could it be the problem with compatibilty between PBI Desktop and TE or PBI and DAX Studio and vice versa? Or is this something else?
Tabular Editor and DAX Studio are used against PBI Desktop model 

Best regards,
George!

**Comment by marcosqlbi** [comment]
It could depend on the library that doesn't store the description for the calculated items.
I will investigate on it.

**Comment by marcosqlbi** [comment]
The fix is published in the library. However, you have to wait for the next release of DAX Studio to export the correct VPAX format and use the VertiPaq Analyzer 2.10 Excel file, which will be released soon.
