### ISSUE TITLE
Vertipaq refresh data not working with Azure Analysis Services - MFA

### ISSUE THREAD

**Issue by virusu** [sql-bi/VertiPaq-Analyzer#29]
Hi,

When opening vpax file from Vertipaq Analyzer 2.10.xlsm, it is 'retreaving data' forever and Excel hangs:
![image](https://user-images.githubusercontent.com/5729468/170459604-3ae1d496-c8ec-49eb-a007-98fda92a22c6.png)
![image](https://user-images.githubusercontent.com/5729468/170459676-aabb0e9e-ccf5-4237-8311-c21ebdf2e425.png)

From DAX Studio I am perfectly able to see/refresh the metrics, but not from Excel.

I am connecting to Azure Analysis Services, and it seems this issue showed up when our organization forced MFA authentication.

Let me know if any additional details are needed.

Kind regards,
Viorel

**Comment by marcosqlbi** [comment]
Are you able to provide a VPAX file without sensitive information that can reproduce the problem?
I've never seen such an issue. The import process in Excel could be slow (much slower than opening the VPAX in DAX Studio) because of the different techniques used to import the data. But it should work - if it doesn't, we should investigate.

**Comment by dgosbell** [comment]
And the vpax file should be completely standalone, it's basically a zip file with some json files inside. The implementation of MFA in AzureAS should have no impact on opening the file in excel.

**Comment by virusu** [comment]
Please find attached vpax file (note that I had to change the extension to upload on github). This is a rather small tabular cube, about 1 GB, and I am not able to open it in Excel Vertipaq Analyzer. I am able to open it however from Dax Studio 2.17.
[DCIS_Hudson_MCA_SSAS_TAB.zip](https://github.com/sql-bi/VertiPaq-Analyzer/files/8832069/DCIS_Hudson_MCA_SSAS_TAB.zip)

**Comment by marcosqlbi** [comment]
I tried to import the vpax file with Vertipaq Analyzer 2.10.xlsm and it worked well.
You can see the result in the file below.
Please, make sure that at the end of the import you click "OK" on the dialog box that says "operation completed". Sometimes it appears behind the Excel window and it seems blocked, while it is not (bring the other window on top, using ALT-TAB or the Windows Taskbar).
[DCIS_Hudson_MCA_SSAS_TAB.zip](https://github.com/sql-bi/VertiPaq-Analyzer/files/8844892/DCIS_Hudson_MCA_SSAS_TAB.zip)
