### ISSUE TITLE
2 columns named 'Rows' in DaxStudio 'Columns' tab

### ISSUE THREAD

**Issue by MartynRamsden** [sql-bi/VertiPaq-Analyzer#3]
The 'Columns' tab of the VertiPaq Analyzer Preview in Dax Studio contains 2 columns named 'Rows'.
The first has no data, the second shows the cardinality of the column.

![Capture](https://user-images.githubusercontent.com/55387656/64951517-f550d780-d875-11e9-85e9-2d085dd4aff0.PNG)

![Capture1](https://user-images.githubusercontent.com/55387656/64951592-23361c00-d876-11e9-90de-e10209216817.PNG)

**Comment by marcosqlbi** [comment]
Will be fixed in the next release of DAX Studio.
