### ISSUE TITLE
Table Size % and Database Size % calculating incorrectly

### ISSUE THREAD

**Issue by MartynRamsden** [sql-bi/VertiPaq-Analyzer#4]
For each table in the model, VertiPaq Analyzer 1.93 contains a reference to a column named 'RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61'. 
This appears to be missing in VertiPaq Analyzer 2.0 which results in the 'Table Size %' and 'Database Size %' being calculated incorrectly.
![Capture](https://user-images.githubusercontent.com/55387656/64954927-d30f8780-d87e-11e9-9b86-f75eca6e983c.PNG)
![Capture1](https://user-images.githubusercontent.com/55387656/64954930-d440b480-d87e-11e9-9ce0-73c541bf260c.PNG)

**Comment by marcosqlbi** [comment]
Hi Martin, thanks for the feedback!
Because that column is often not interesting and very small, we filtered it out by default in 2.0.
If you change the filter in cell C1 you can restore it.
Thanks again for testing VertiPaq Analyzer 2.0!!

**Comment by MartynRamsden** [comment]
Thanks for the clarification Marco - I should have spotted the filter!
