### ISSUE TITLE
Unable to 'View Metrics' in DaxStudio if data model contains a Measures Table

### ISSUE THREAD

**Issue by MartynRamsden** [sql-bi/VertiPaq-Analyzer#5]
If the data model contains a measure table (indicated by a small calculator icon in Power BI) in which all columns have been deleted and it only contains measures, the View Metrics options does not work in DaxStudio - the VertiPaq Analyzer pane doesn't open.
When creating a measure table, if the column is hidden rather than deleted it works ok.

I guess it's safe to say that all tables must have at least one column for the tool to work correctly?!

N.B. - I no longer use measure tables in Power BI due to their incompatibility with Q&A but was testing an old model which used this technique and thought it was worthy of note.

**Comment by marcosqlbi** [comment]
Will be fixed in the next release of DAX Studio

**Comment by dgosbell** [comment]
This should be fixed in the next release. I've checked in a fix to the source to cater for this scenario
