### ISSUE TITLE
Error: The specified Power BI workspace is not found

### ISSUE THREAD

**Issue by srinivas1612** [sql-bi/VertiPaq-Analyzer#67]
I encountered an exception while trying to connect to a Power BI workspace using the following code:

```
public async Task<Dax.ViewVpaExport.Model> VertiPaqAnalyzer(string workspace, string dataset)
{
    try
    {
        // Get access token
        var pbiAccessToken = GetPowerBIAccessToken();

        string connectionString = $"Data Source=powerbi://api.powerbi.com/v1.0/myorg/{workspace};Initial Catalog={dataset};";

        // Set access token in the connection string
        connectionString += $";Password={pbiAccessToken}";

        var daxModel = Dax.Metadata.Extractor.TomExtractor.GetDaxModel(connectionString, "TestDaxModel", "0.2", true, 10, analyzeDirectQuery: true);

        Dax.ViewVpaExport.Model viewVpa = new Dax.ViewVpaExport.Model(daxModel);

        return viewVpa;
    }
    catch
    {
        throw;
    }
}

```

The exception message I received is "The specified Power BI workspace is not found."

![image](https://github.com/sql-bi/VertiPaq-Analyzer/assets/9430544/e7f36186-0804-4bc3-96e7-5c779d3f197b)

I have verified that the workspace name and dataset name are correct, and I am able to connect successfully when I comment out the following line:

`connectionString += $";Password={pbiAccessToken}";
`

However, I need to provide the access token in the connection string for authentication.

Can someone please help me understand why I am receiving this exception and how to resolve it?

Thanks

**Comment by albertospelta** [comment]
Hi @srinivas1612 I saw that you closed the issue. Have you been able to resolve it? If so, how ? Thanks!

**Comment by srinivas1612** [comment]
The issue with my access token. Thanks.
