### ISSUE TITLE
Referential integrity violation example queries lead to OOM errors

### ISSUE THREAD

**Issue by awbarbeau** [sql-bi/VertiPaq-Analyzer#8]
Hi,

When running the current referential integrity violation example queries in DAX Studio 2.11.2, against high cardinality columns, the current implementation of SAMPLE( ) against a column can lead to Out Of Memory (OOM) errors and other compressed column decompression errors on AAS.

ex.
`
EVALUATE
CALCULATETABLE (
    SELECTCOLUMNS (
        SAMPLE (
            3,
            DISTINCT ( 'Many Side Table'[Key Column] ),
            'Many Side Table'[Key Column], ASC
        ),
        "RelationshipId", 101,
        "MissingValue", 'Many Side Table'[Key Column]
    ),
    ISBLANK ( 'One Side Table'[Customer SK] ),
    USERELATIONSHIP ( 'Many Side Table'[Key Column], 'One Side Table'[Key Column] )
)`

Based conversations with @dgosbell, I've put together an alternative implementation for high cardinality columns, that reliably avoids materialization of high cardinality columns.

`
EVALUATE
SELECTCOLUMNS (
    TOPNSKIP (
        3,
        0, 
        CALCULATETABLE (
            'Many Side Table',
            ISBLANK ( 'One Side Table'[Key Column] ),
            USERELATIONSHIP ( 'Many Side Table'[Key Column], 'One Side Table'[Key Column] )
        ),
        VALUES ( 'One Side Table'[Key Column] ), ASC
    ),
    "RelationshipId", 101,
    "Examples", 'Many Side Table'[Key Column]
)
`

This query avoids the materialization issues with the SAMPLE( ) approach. The use of "0" in the 2nd argument may not be ideal, but is used for lack of a better alternative based on a pure DAX approach.

I attempted a VAR based approach to provide to the second argument, however I found that TOPNSKIP( ) does not allow arguments based on a VAR, in either DAX Studio or SSMS, for the 2nd argument.

VAR for reference:
`
VAR midpoint =
        INT (
            COUNTROWS (
                CALCULATETABLE (
                    VALUES ( 'Many Side Table'[Key Column] ),
                    ISBLANK ( 'One Side Table'[Key Column] ),
                    USERELATIONSHIP ( 'Many Side Table'[Key Column], 'One Side Table'[Key Column] )
                )
            ) / 2
        )
`

The particular OOM error I encountered occurred for a column with 113 Million distinct values. I doubt this issue would recur for relationship columns with sub 10 million distinct values, however I will provide updates on the particular error for the high cardinality column if relevant.

**Comment by awbarbeau** [comment]
I will also call out that the 113 Million distinct value column being used in an AAS relationship is a bad practice, and based on a model that I am now supporting as-is without any modification.

**Comment by dgosbell** [comment]
TOPNSKIP is only available if the engine version is >= 13 (ie SSAS 2016 or later) so we may need to check if a TOPN variation would also work

**Comment by awbarbeau** [comment]
I was able to write a TOPN version, but it is 10-30x slower than the TOPNSKIP version. 

`
EVALUATE
CALCULATETABLE (
    SELECTCOLUMNS (
        TOPN ( 3, VALUES ( 'Many Side Table'[Key Column] ) ),
        "RelationshipId", 101,
        "MissingValue", 'Many Side Table'[Key Column]
    ),
    ISBLANK ( 'One Side Table'[Key Column] ),
    USERELATIONSHIP ( 'Many Side Table'[Key Column], 'One Side Table'[Key Column] )
)
`

**Comment by dgosbell** [comment]
> I was able to write a TOPN version, but it is 10-30x slower than the TOPNSKIP version, at least for a 100+ million cardinality row column.

I don't think that will be too much of an issue, we would only fall back to something like that if we are running against one of the older engines like SSAS 2012/2014 or PowerPivot

**Comment by marcosqlbi** [comment]
I just published a new update of the VertiPaq Analyzer library that solves this issue. When the column has more than 1000 unique invalid keys, there is a technique based on TOPNSKIP if the model compatibility level is >= 1200 and just TOPN for older models and PowerPivot.
@dgosbell if you update the VertiPaq Analyzer packages in DAX Studio, the next release will include the fix.
Thanks!
